type: quran
quran_simple:
 de_aburida:
  english_name: German
  native_name: Deutch
  dir: ./lib/qwerty/de_aburida
  is_pack: 1

 sq_nahi:
  english_name: Albanian
  native_name: Shqip
  dir: ./lib/qwerty/sq_nahi
  is_pack: 1

 ar_jalalayn:
  english_name: Arabic
  native_name: العربية
  dir: ./lib/qwerty/ar_jalalayn
  is_pack: 1